### PR TITLE
Feature/New Navbar Styling [EOSF-618]

### PR DESCRIPTION
**Pull request by pattisdr**
# Ticket
https://openscience.atlassian.net/browse/EOSF-618

# Purpose

The OSF Navbar has been redesigned and implemented as a resuable Ember-OSF component that can be shared among our Ember applications.  The navbar will need to be implemented separately OSF-side.   Styles should be moved to OSF-style so they can be shared among our products.

# Changes
Moves styles from Ember-OSF navbar widget to style guide.

image

### CODE REVIEW

**Comment by pattisdr** [comment]
@sloria, why did you close this? Do I need to make a new PR?

**Comment by sloria** [comment]
@pattisdr

**Comment by sloria** [comment]
@pattisdr Sorry about that. I removed the `develop` branch, which closed all PRs targeting it. I've changed the base to master and reopened.

**Comment by pattisdr** [comment]
I see, thanks!

**Comment by caneruguz** [comment]
@pattisdr Looks good to me. Thanks for commenting and using SASS features.

**Pull request merged**
